[28/Jan/2018:04:18:26] (create_db) Connected successfully
